apiVersion: apps/v1
kind: Deployment
metadata:
  name: hike-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hike
  template:
    metadata:
      labels:
        app: hike
    spec:
      containers:
        - image: lucasahj/hike #to be changed
          name: hike
          ports:
            - containerPort: 8080
              name: server

---

apiVersion: v1
kind: Service
metadata:
  name: hike
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: hike
