kumuluzee:
  name: hike-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/HikeDS
      connection-url: jdbc:postgresql://localhost:5432/hike
      username: dbuser
      password: postgres
  health:
    #checks:
      #data-source-health-check:
        #type: liveness
        #jndi-name: jdbc/ImageMetadataDS
  metrics:
    web-instrumentation:
      - name: hike-endpoint
        url-pattern: /v1/hikes/*
rest-properties:
  broken: false

